name: release

on:
  push:
    branches:
      - "main"
    paths:
      - "Dockerfile"

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push dev image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: okteto/aws-sam
